//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTestimonial
    {
        public int TestimonalName_ { get; set; }
        public string Description1 { get; set; }
        public string TestimonialName { get; set; }
        public string Description2 { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string TestimonialID { get; set; }
    }
}
